# Generated by Django 5.1.6 on 2025-10-09 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Judge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("court", models.CharField(max_length=255)),
                ("availability", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="Lawyer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("busy_slots", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_number", models.CharField(max_length=50, unique=True)),
                (
                    "case_type",
                    models.CharField(
                        choices=[
                            ("civil", "Civil"),
                            ("criminal", "Criminal"),
                            ("family", "Family"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("filed_in", models.DateField()),
                ("urgency", models.FloatField(default=0.5)),
                ("estimated_duration", models.IntegerField(default=60)),
                ("priority", models.FloatField(default=0.0)),
                (
                    "assigned_judge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="scheduler.judge",
                    ),
                ),
                ("lawyers", models.ManyToManyField(blank=True, to="scheduler.lawyer")),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("room", models.CharField(default="Courtroom 1", max_length=50)),
                ("version", models.IntegerField(default=1)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="scheduler.case"
                    ),
                ),
                (
                    "judge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scheduler.judge",
                    ),
                ),
            ],
        ),
    ]
