# Generated by Django 5.1.6 on 2025-10-09 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="case",
            old_name="filed_in",
            new_name="filed_on",
        ),
    ]
