# Generated by Django 5.1.6 on 2025-10-09 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0002_rename_filed_in_case_filed_on"),
    ]

    operations = [
        migrations.RenameField(
            model_name="case",
            old_name="filed_on",
            new_name="filed_in",
        ),
    ]
