# Generated by Django 5.1.6 on 2025-10-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0003_rename_filed_on_case_filed_in"),
    ]

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("embedding", models.JSONField(default=list)),
                ("source", models.CharField(default="internal", max_length=100)),
            ],
        ),
    ]
