# Generated by Django 5.0.3 on 2025-10-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
