# Generated by Django 5.1.6 on 2025-10-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0005_case_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="judge",
            name="experience_years",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="judge",
            name="max_daily_cases",
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name="judge",
            name="specialization",
            field=models.CharField(
                choices=[
                    ("criminal", "Criminal Law"),
                    ("civil", "Civil Law"),
                    ("family", "Family Law"),
                    ("commercial", "Commercial Law"),
                    ("general", "General Practice"),
                ],
                default="general",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="judge",
            name="working_hours",
            field=models.JSONField(default={"end": "19:00", "start": "15:30"}),
        ),
        migrations.AddField(
            model_name="lawyer",
            name="experience_years",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lawyer",
            name="hourly_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="lawyer",
            name="max_cases",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="lawyer",
            name="specialization",
            field=models.CharField(
                choices=[
                    ("criminal", "Criminal Law"),
                    ("civil", "Civil Law"),
                    ("family", "Family Law"),
                    ("corporate", "Corporate Law"),
                    ("general", "General Practice"),
                ],
                default="general",
                max_length=50,
            ),
        ),
    ]
