# Generated by Django 5.1.6 on 2025-11-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0006_judge_experience_years_judge_max_daily_cases_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="judge",
            name="working_hours",
            field=models.JSONField(default=dict),
        ),
    ]
