# Generated by Django 5.1.6 on 2025-11-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0007_alter_judge_working_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="is_resolved",
            field=models.BooleanField(default=False),
        ),
    ]
